### ISSUE TITLE
segmentation fault while importing dtls with python3

### ISSUE THREAD

**Issue by anwesha25** [mobius-software-ltd/pyton3-dtls#7]
I had installed python3-dtls with pip3. But importing dtls with python3 results is segmentation fault. 

ubuntu@localhost:~$ pip3 install python3-dtls --no-cache-dir
Collecting python3-dtls
  Downloading https://files.pythonhosted.org/packages/01/6c/22b421f665f9013ef6271dd8121ac63c6b7e48ffbab47fb2cc399d5ea6b6/python3_dtls-1.0.3-py3-none-any.whl (99kB)
    100% |████████████████████████████████| 102kB 108kB/s
Installing collected packages: python3-dtls
Successfully installed python3-dtls-1.0.3
ubuntu@localhost:~$

ubuntu@localhost:~$ python3
Python 3.6.9 (default, Apr 18 2020, 01:56:04)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dtls
Segmentation fault

I am using:
Ubuntu 18.04
OpenSSL 1.1.1  11 Sep 2018
Python 3.6.9

**Comment by yulianoifa-mobius** [comment]
Hi @anwesha25 Please test release 1.3.0 which should be working with openssl 1.1.1 , we have tested with python 3.8

**Comment by yulianoifa-mobius** [comment]
pip3 install python3-dtls --no-cache-dir
Collecting python3-dtls
  Downloading python3_dtls-1.3.0-py3-none-win_amd64.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 1.3 MB/s
Installing collected packages: python3-dtls
Successfully installed python3-dtls-1.3.0


python3
Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import dtls
>>>
